show DATABASES;

CREATE DATABASE starwars;

--CRIA O DATABASE SE ELE NÃO EXISTIR
CREATE DATABASE if not EXISTS starwars;

DROP DATABASE teste;

--DELETA O DATABASE SE ELE EXITIR
DROP DATABASE IF EXISTS teste;

